language: node_js

node_js:
  - "5"

before_script:
  - npm install -g bower gulp-cli mocha
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - npm run-script start

script:
  - gulp coverage_frontend
  - npm run-script test-server
  - npm run-script test-client

services: mongodb
