language: node_js

node_js:
  - "5"

before_script:
  - npm install -g bower gulp-cli mocha
  - bower install
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run-script server &
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - gulp coverage_frontend
  - npm run-script test-server
  - npm run-script test-client

services: mongodb
