language: node_js

node_js:
  - "6.9.1"


env:
#- NODE_ENV="production"
#- MONGOHQ_URL="mongodb://localhost/hosonto"

before_script:
  - npm install -g bower gulp-cli mocha
  - bower install
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
#  - npm run-script build-dev

script:
  - npm run-script coverage-server
  - npm run-script test-server
  - npm run-script dev &
  - sleep 3 # give Web server some time to bind to sockets, etc
  - npm run-script test-client

services: mongodb
